version: '3'

services:
  django:
    build:
      context: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    container_name: booblik
    env_file:
      - .env
    ports:
      - '8000:8000'
    restart: always
    depends_on:
      - postgres
      - redis
      - migration
    volumes:
      - static_volume:/usr/src/app/back_static
      - media_volume:/usr/src/app/back_media

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Bishkek

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/back-static
      - media_volume:/usr/src/app/back-media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6380:6379"

  celery:
    build:
      context: .
    command: celery -A core worker -l INFO
    depends_on:
      - django
      - redis
      - migration

  celery-beat:
    build:
      context: .
    command: celery -A core beat -l INFO
    depends_on:
      - django
      - redis
      - celery
      - migration

  migration:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    depends_on:
      - postgres

volumes:
  postgres_data:
  static_volume:
  media_volume:
